travis:
  secure:
    BINSTAR_TOKEN: jAclqtXWlolNqA8ekaCF1jyrteHVcvt+Z6BifNX9yZX0UbW7W/fL8AYF0W3IuJOb0H+Jm0pDCtKr242w/dsUJ34C5O/almeE7yrs385+6JrLLufiFUcu5Q2sJvte3ZrGcLFimfR+656wywZpLCIgoIEnL54DdmmT59WE749lFmuUJtpaku6QgK+Lbllgm5KexnHzHW7zHy/AQrUCGl1cptzk+mK2bxaQdERhmxyfkGEHV4CSeCkzNUmVDsVfRR7eBe2l/qjtMNDNz+4nYekF1dXSOf4KXfojPbLy8Dh4fvnCfPZZO9BP1tz5Zeo0I1BZPT2sIA4LeRSpfkIeb2feQIb0j9tCr2I1j5tDGA9chHaptEYVz0H4X6YgfiQXHPCdJ0CEg+TVNFf+yJX2IDDOSZ8TLyqTxavZaO/vtXBbGByG2IMYEwycVTHqzCla5jHazSqf70yGySBC+ajFUKz4D/cyn64BSf2iyMQ69ukPVKa6H99DAWSCCyKoG0jhSCC/SWjEAaNN/9xy0MdWsT5o9GeqAfVNJ7MyUxHVLsnVBdF47XiZL964LamoY+PMP4/JBYbViQ7Bl/7PLDIsCVe0IumG914rbi6rdJf1uU8WZpUhxz6Fj0Nyq1LOxd1x1VU+QkDQooSDsprDmMpZaDAIaVVCnvuS/41MUPZTs6uQ8eg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
